FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["Directory.Build.props", "./"]
COPY ["src/Intropy.IdempotencyService.csproj", "src/"]
COPY ["test/Intropy.IdempotencyService.Test.csproj", "test/"]

RUN dotnet restore "src/Intropy.IdempotencyService.csproj"
RUN dotnet restore "test/Intropy.IdempotencyService.Test.csproj"

COPY ./src ./src
COPY ./test ./test

RUN dotnet build "./src/Intropy.IdempotencyService.csproj" -c $BUILD_CONFIGURATION -o /app/build
RUN dotnet test "./test" --configuration $BUILD_CONFIGURATION --no-restore --verbosity normal


FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./src/Intropy.IdempotencyService.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Intropy.IdempotencyService.dll"]
