apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ include "idempotency-service.stateStoreName" . }}
spec:
  type: {{ .Values.stateStore.type }}
  version: {{ .Values.stateStore.version }}
  metadata:
    - name: keyPrefix
      value: "none"
    {{- with .Values.stateStore.metadata }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
scopes:
  - {{ include "idempotency-service.fullname" . }}