name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dotnet:
    name: Build, Test & Pack
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build

      - name: Pack
        run: dotnet pack -c Release --no-build -o ./nupkg -p:Version=0.0.0-ci.${{ github.run_number }}

      - name: Upload packages
        uses: actions/upload-artifact@v7
        with:
          name: nupkg
          path: ./nupkg

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build service image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: idempotency-service:ci

  helm:
    name: Lint Helm chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Helm lint
        run: helm lint charts/idempotency-service

      - name: Helm template
        run: helm template charts/idempotency-service
